services:
  bot:
    # Build the image from the Dockerfile in the current directory
    build: .

    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./bot.log:/app/bot.log

    env_file: ".env"

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/
            - db.sqlite3
            - bot.log

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
