[project]
name = "indusgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.77.0",
    "telethon>=1.40.0",
]

[dependency-groups]
dev = [
    "aiogram>=3.20.0.post0",
    "ruff>=0.11.8",
]
